### ISSUE TITLE
Getting a System.InvalidOperationException: Only one HostingEnvironment is allowed in an AppDomain

### ISSUE THREAD

**Issue by rajeshpandalss** [vadimzozulya/FakeHttpContext#9]
One my tests would fail when running the entire test suite. It will fail with the following.

`Only one HostingEnvironment is allowed in an AppDomain.`

Rerunning the individual test will make it a success. 
I am using it the following way.

`using (new FakeHttpContext.FakeHttpContext())`

 {
`new Action(() => _fooService.SomeMethod()).ShouldThrow<BadRequestException>();`
                }

**Comment by vadimzozulya** [comment]
@rajeshpandalss, I can reproduce the issue with simple test:

```csharp
var tasks = new List<Task>();
for(var i=0; i<100; i++)
{
    tasks.Add(
        Task.Run(() =>
             {
                 using (new FakeHttpContext())  { }
             }));
}
Task.WaitAll(tasks.ToArray());
```
The issue is reproducible even with less number of tasks, but with less probability. 
It means that `FakeHttpContext` is not completely compatible with parallel execution.
I believe you run your tests in parallel, let me know if I'm wrong.

I didn't manage to fix it fast, so as a workaround, I'd suggest you to disable parallel execution for tests with `FakeHttpContext` until I found a proper fix.

Sorry for inconvenience.

**Comment by rajeshpandalss** [comment]
All good. I have created my own httpcontextmock. Since i needed only the
session object, it was quick. Thanks for the insight though. Really
appreciate the effort.

**Comment by vadimzozulya** [comment]
Unfortunately to fix such random fails I had to add some locks, and so, all tests using `FakeHttpContext` will not be run in parallel regardless test runner settings. There is no other options because `System.Web.Hosting.HostingEnvironment` can't be instantiated several times, and it uses static fields inside and parallel instances of `FakeHttpContext` even will affect each others.
